baseURL:  https://darktable-org.github.io/dtdocs/
defaultContentLanguage: en-us
defaultContentLanguageInSubdir: true
languages:
  en-us:
    title: darktable 3.7 (development) user manual
    languageName: English
    weight: 1
  fr-fr:
    title: darktable 3.7 (development) user manual
    languageName: Français
    weight: 2
  de:
    title: darktable 3.7 (development) user manual
    languageName: German
    weight: 4
  eo:
    title: darktable 3.7 (development) user manual
    languageName: Esperanto
    weight: 5
  es:
    title: darktable 3.7 (development) user manual
    languageName: Espanol
    weight: 6
  gl:
    title: darktable 3.7 (development) user manual
    languageName: Galician
    weight: 7
  it:
    title: darktable 3.7 (development) user manual
    languageName: Italian
    weight: 8
  pl:
    title: darktable 3.7 (development) user manual
    languageName: Polish
    weight: 9
  pt-br:
    title: manual do usuário darktable 3.7 (desenvolvimento)
    languageName: Português
    weight: 10
  uk:
    title: darktable 3.7 (development) user manual
    languageName: Ukrainian
    weight: 11
theme:
  - hugo-darktable-docs-pdf-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    renderer:
      unsafe: true
