baseURL:  https://darktable-org.github.io/dtdocs/
defaultContentLanguage: en-us
languages:
  en-us:
    title: darktable 3.5 (dev) user manual
    weight: 1
  fr-fr:
    title: darktable 3.5 (dev) user manual
    weight: 2
  de:
    title: darktable 3.5 (dev) user manual
    weight: 4
  eo:
    title: darktable 3.5 (dev) user manual
    weight: 5
  es:
    title: darktable 3.5 (dev) user manual
    weight: 6
  gl:
    title: darktable 3.5 (dev) user manual
    weight: 7
  it:
    title: darktable 3.5 (dev) user manual
    weight: 8
  pl:
    title: darktable 3.5 (dev) user manual
    weight: 9    
theme:
  - hugo-darktable-docs-theme
markup:
  highlight:
    style: algol_nu
outputs:
  home:
    - HTML
    - RSS
    - JSON
module:
  mounts:
    - source: ./themes//hugo-darktable-docs-theme/assets/node_modules/fork-awesome/fonts
      target: static/fonts
