baseURL:
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable 3.6 user manual
    languageName: English
    weight: 1
  de:
    title: darktable 3.6 user manual
    languageName: German
    weight: 4
  es:
    title: darktable 3.6 user manual
    languageName: Espanol
    weight: 6
  uk:
    title: darktable 3.6 user manual
    languageName: Ukrainian
    weight: 11
theme:
  - hugo-darktable-docs-epub-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true
      xHTML: true

disableKinds:
  - sitemap
  - taxonomy
  - term

uglyURLs: true
relativeURLs: true

mediaTypes:
  application/xhtml+xml:
    suffixes:
      - xhtml
  application/opf+xml:
    suffixes:
      - opf
  application/x-dtbncx+xml:
    suffixes:
      - ncx

outputFormats:
  XHTML:
    mediaType: application/xhtml+xml
    isHTML: true
    permalinkable: true
    baseName: toc
  OPF:
    mediaType: application/opf+xml
    isHTML: true
    permalinkable: true
    baseName: content
  NCX:
    mediaType: application/x-dtbncx+xml
    isHTML: true
    permalinkable: true
    baseName: toc

outputs:
  page:
    - HTML
  home:
    - OPF
    - NCX
    - HTML
    - XHTML
  section:
    - HTML

params:
  description: The user manual for darktable
  creator: darktable
  author: darktable
  publisher: darktable
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
