baseURL:  https://darktable-org.github.io/dtdocs/
languageCode: en-us
title: darktable 3.4 user manual
theme:
  - hugo-darktable-docs-pdf-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    renderer:
      unsafe: true
