baseURL:  https://elstoc.github.io/dtdocs/
languageCode: en-us
title: darktable user manual
theme:
  - hugo-darktable-docs-theme
  - hugo-bootstrap-bare
markup:
  highlight:
    style: algol_nu
outputs:
  home:
    - HTML
    - RSS
    - JSON
