baseURL:  https://darktable-org.github.io/dtdocs/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable 3.6 user manual
    languageName: English
    weight: 1
  de:
    title: darktable 3.6 user manual
    languageName: German
    weight: 4
  es:
    title: darktable 3.6 user manual
    languageName: Espanol
    weight: 6
  uk:
    title: darktable 3.6 user manual
    languageName: Ukrainian
    weight: 11
theme:
  - hugo-darktable-docs-pdf-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    renderer:
      unsafe: true
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
