name: Pull Request tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pull-request-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-env -f '<nixpkgs>' -iA hugo yarn python38Packages.weasyprint git linkchecker perlPackages.Po4a

      - name: Install assets
        run: cd themes/hugo-darktable-docs-theme/assets/ && yarn install

      - name: Generate translated files
        run: cd tools && bash generate-translations.sh --no-update

      - name: Build PDF
        run: hugo server --disableFastRender -verbose --config config-pdf.yaml & sleep 5 && weasyprint -v http://localhost:1313/dtdocs/index.html ./public/darktable_user_manual.pdf && pkill hugo

      - name: Run linkchecker
        run: hugo server --disableFastRender -verbose --config config-pdf.yaml & sleep 5 && linkchecker --check-extern --no-status http://localhost:1313/dtdocs/index.html && pkill hugo
